name: Deployment on AWS

on:
  push:
    branches:
      - main

jobs:

  Checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Teste
      run: |
        cd app/
        npm install
        npm test